support_request/config/routes.rb
Rails.application.routes.draw do

  get   '/requests/new'   => 'requests#new', as: :new_request
  post  '/requests'       => 'requests#create'
  get   '/requests'       => 'requests#index'
  get   '/requests/:id'   => 'requests#show', as: :request
  get   '/requests/edit'  => 'requests#edit'

end

support_request/app/models/request.rb
class Request < ActiveRecord::Base
end

support_request/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

support_request/app/controllers/requests_controller.rb
class RequestsController < ApplicationController

  def new
    @request = Request.new
  end

  def create
    request_params = params.require(:request).permit(:name, :email, :department, :message)
    @request = Request.new(request_params)

    if @request.save
      redirect_to requests_path(@request)
    else
      render :new
    end
  end

  def show
    @request = Request.find params(:id)
  end

  def index
    @request = Request.all
  end

end

support_request/app/helpers/application_helper.rb
module ApplicationHelper
end

support_request/app/helpers/requests_helper.rb
module RequestsHelper
end

support_request/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SupportRequest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= link_to "Index", requests_path %>
  <%= link_to "New", new_request_path %>

<%= yield %>

</body>
</html>

support_request/app/views/requests/edit.html.erb
<h1>Edit Support Request</h1>

<%= @request.errors.full_messages.join(", ") %>

<%= form_for @request do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div><br>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div><br>
  <div>
    <%= f.label :department %>
    <%= radio_button_tag(:department, "Sales") %>
    <%= label_tag(:Sales) %>
    <%= radio_button_tag(:department, "Marketing") %>
    <%= label_tag(:Marketing) %>
    <%= radio_button_tag(:department, "Technical") %>
    <%= label_tag(:Technical) %>
  </div><br>
  <div>
    <%= f.label :message %>
    <%= f.text_area :message %>
  </div><br>
  <%= f.submit :Save%>
<% end %>

support_request/app/views/requests/index.html.erb
<h1>Support Requests</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Department</th>
    <th>Message</th>
    <th>Actions</th>
  </tr>
  <% @request.each do |request| %>
  <tr>
    <td><%= link_to request.name, requests_path(request) %></td>
    <td><%= mail_to request.email %>
    <td><%= request.message %>
  </tr>
  <% end %>
</table>

support_request/app/views/requests/new.html.erb
<h1>New Support Request</h1>

<%= @request.errors.full_messages.join(", ") %>

<%= form_for @request do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div><br>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div><br>
  <div>
    <%= f.label :department %>
    <%= radio_button_tag(:department, "Sales") %>
    <%= label_tag(:Sales) %>
    <%= radio_button_tag(:department, "Marketing") %>
    <%= label_tag(:Marketing) %>
    <%= radio_button_tag(:department, "Technical") %>
    <%= label_tag(:Technical) %>
  </div><br>
  <div>
    <%= f.label :message %>
    <%= f.text_area :message %>
  </div><br>
  <%= f.submit :Save%>
<% end %>

support_request/app/views/requests/show.html.erb
<!-- <h1><%= @request.name %></h1>

<h2><%= @request.email %></h2>

<p><%= @request.department %></P>

<p><%= @request.message %></p>

<p><%= @request.created_at %></p> -->

<h1><%= @request.title %></h1>
<p><%= @request.body %></p>
<p>View Count: <%= @request.view_count %></p>

<%= link_to "Edit", edit_request_path(@request) %>
<%= link_to "Delete", request_path(@request),
                      method: :delete,
                      data: {confirm: "Are you sure?"} %>